#!/bin/bash

#SBATCH -J ea26799_HW2_p1
# job name

#SBATCH -o results_%j
# output and error file name (%j expands to jobID)

#SBATCH -n 1
# total number of mpi tasks requested

#SBATCH -p gpudev
# queue (partition) -- normal, development, etc.

#SBATCH -t 00:60:00
# run time (hh:mm:ss)

#SBATCH -A Parallel-Algorithms
#SBATCH --mail-user=ericaddison@gmail.com

#SBATCH --mail-type=begin
# email me when the job starts

#SBATCH --mail-type=end
# email me when the job finishes

../bin/cudaFFT.out
